### ISSUE TITLE
"iphone 6 plus simulator" Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by satels** [kivy/kivy-ios#161]
```
static void
update_refs(PyGC_Head *containers)
{
    PyGC_Head *gc = containers->gc.gc_next;
    for (; gc != containers; gc = gc->gc.gc_next) {
        assert(gc->gc.gc_refs == GC_REACHABLE);
        gc->gc.gc_refs = Py_REFCNT(FROM_GC(gc)); <---- Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```

On simple "iphone 6 simulator" - all work.
##

**Comment by satels** [comment]
![2015-09-24 18 18 26](https://cloud.githubusercontent.com/assets/220572/10077616/c0732262-62e9-11e5-87b9-a3a6e27a9e3f.png)

**Comment by satels** [comment]
and from app store reviewers:
```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x4074000000000018
Triggered by Thread:  0

```

**Comment by satels** [comment]
It error reproduced after install pyobjus recipe.

**Comment by Zen-CODE** [comment]
Just tested. A basic Kivy app runs without issues in the iPhone6 plus simulator. There must be something specific here. But without more info, we can't take any action here.

In order to fix issues, we need to be able to reproduce them. Other apps work fine. If you still get this error, please re-open the ticket with a reproducible example (in order to establish it's not your app that is not misbehaving).
