### ISSUE TITLE
Kivy iOS Full-screen disabling [$50]

### ISSUE THREAD

**Issue by ghost** [kivy/kivy-ios#189]
Hi Team,

Upon deploying to iOS, my app covers the status bar and i can no longer see the time and battery percentage.

I disabled the fullscreen options in the plist file in xcode but the app still continues to run in fullscreen mode.

How can i enable the status bar in iOS for Kivy apps?
##

**Comment by vjgaero** [comment]
Attempted to use fullscreen=0 for buildozer spec but seems its only applicable to android devices

**Comment by vjgaero** [comment]
@tito can you clarify with 2048? It appears buildozer init puts fullscreen under android specifics. It does not work under iOS specifics but i can see that in your 2048 spec file, fullscreen is under just general settings. Is that it?

**Comment by gorgonaut04** [comment]
There are a few different places you need to make changes currently to support this:

In xcode, click the name of your project in the left panel to see the "General" options in the main window:
- Scroll down to "deployment info" section
- For iPhone, set status bar style to default (I don't think it matters since it is overridden in code numerous times). If you want to hide status bar at startup (not sure you have a choice not to), check "hide status bar"
- If you don't allow all orientations, you must check "Requires Fullscreen". This just prevents split windows on larger/newer devices, and isn't related to the status bar, per se. Probably good to check anyway.
- for iPad, check "Hide during application launch" (the inconsistent naming of these similar options is a disaster!) and most likely "Requires Fullscreen" as well.

In bridge.m (you can experiment with alternate parameters here):
```
- (void) showStatusBar {
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleLightContent animated:NO];
    [[UIApplication sharedApplication] setStatusBarHidden:NO
                                            withAnimation:UIStatusBarAnimationNone];
}
```
Kivy Code:
- For any screen loaded with the root widget:
```        
on_pre_enter:
    if platform == 'ios': \
    self.size_hint_y = None; \
    self.height = root.height - dp(20)
```
Python Code:
- For any dynamically-loaded screen:
```
from kivy.metrics import dp
# Adds space for status bar on iOS
if platform == 'ios':
    new_screen.size_hint_y = None
    new_screen.height = self.height - dp(20)
```
- In root widget Class definition:
```
from kivy import platform
from kivy.clock import Clock
from kivy.logger import Logger

class TestApp(App):
    try:
        if platform == 'ios':
            from pyobjus import autoclass
            Bridge = autoclass('bridge')
            br = Bridge.alloc().init()
    except:
        Logger.error("bridge.m missing showStatusBar.")

    def on_start(self):
        # Show the iOS status bar
        try:
            if platform == 'ios':
                self.br.showStatusBar()
        except:
            Logger.error("bridge.m missing showStatusBar.")

    def on_pause(self):
        try:
            if platform == 'ios':
                self.br.showStatusBar()
        except:
            Logger.error("bridge.m missing showStatusBar.")
        # I know this is a mess, but I really do need to do this again on the next frame to get it to work in my app
        try:
            if platform == 'ios':
                Clock.schedule_once(self.br.showStatusBar, 0)
        except:
            Logger.error("bridge.m missing showStatusBar.")

        return True

    def on_resume(self):
        try:
            if platform == 'ios':
                Clock.schedule_once(self.br.showStatusBar, 0)
        except:
            Logger.error("bridge.m missing showStatusBar.")

        return
```

**Comment by gorgonaut04** [comment]
That should be it, but feel free to call showStatusBar more often if needed, and experiment with waiting a frame before doing so. Let me know how it goes!

**Comment by gorgonaut04** [comment]
Can this issue be closed?

**Comment by Zen-CODE** [comment]
@ghost. Bump. Have you tried the suggested code above? gotgonaut04 has put a lot of impressive work into this to help. It's only polite to acknowledge? :-)

**Comment by d0mj** [comment]
I couldn't get the above to work.  However, a patch to sdl2 can force the status bar to be visible always (apply the patch in the sdl2 recipe).

```
--- SDL2-2.0.5/src/video/uikit/SDL_uikitviewcontroller.m        2016-10-20 04:56:26.000000000 +0100
+++ SDL2-2.0.5/src/video/uikit/SDL_uikitviewcontroller.m        2017-02-27 23:21:02.000000000 +0000
@@ -158,9 +158,14 @@
     return ([self supportedInterfaceOrientations] & (1 << orient)) != 0;
 }
 
+- (UIStatusBarStyle)preferredStatusBarStyle {
+    return UIStatusBarStyleBlackOpaque; // your own style
+}
+
 - (BOOL)prefersStatusBarHidden
 {
-    return (window->flags & (SDL_WINDOW_FULLSCREEN|SDL_WINDOW_BORDERLESS)) != 0;
+    //return (window->flags & (SDL_WINDOW_FULLSCREEN|SDL_WINDOW_BORDERLESS)) != 0;
+    return NO;
 }
 #endif
 
```

I then wrapped the app widgets in a custom ScreenManager so that it behaves as expected when the device is rotated.

```
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy import platform as OSPlatform
from kivy.metrics import dp
from kivy.properties import NumericProperty
from kivy.core.window import Window

class my_screen_manager(ScreenManager):

    max_height = NumericProperty()

    def show_status_bar(self):
        if OSPlatform == 'ios':
            current_screen = self.get_screen(self.current)
            current_screen.size_hint_y = None
            current_screen.height = self.max_height - dp(20)

    def on_width(self, *args):
        if OSPlatform == 'ios':
            self.max_height = Window.height
            self.show_status_bar()
```

Which results in this:
![simulator screen shot 8 mar 2017 21 46 02](https://cloud.githubusercontent.com/assets/17249386/23726097/f17a8f72-044a-11e7-8dd8-ff09a338732a.png)

I've yet to play with a pyobjus solution, but the above should point the way.

**Comment by Zen-CODE** [comment]
This issue should now be resolved with recent changes. Please update your checkout to the latest version and re-open if the issue persists.

Thanks

**Comment by AndreMiras** [comment]
@Zen-CODE @misl6 maybe you could claim the bounty this time

**Comment by Zen-CODE** [comment]
That should definitely be @misl6 is anyone...:-)

**Comment by misl6** [comment]
I'm claiming it and devolving it directly into the Kivy budget in order to improve and expand iOS related features as discussed on discord.
