### ISSUE TITLE
iTunes validation Error ITMS-90171: Invalid Bundle Structure

### ISSUE THREAD

**Issue by Zen-CODE** [kivy/kivy-ios#193]
When trying to publish an app in iTunes, the validation step throws many errors arouns ".so.o" files, e.g.

myapp/lib/python2.7/site-packages/kivy/graphics/svg.so.o
myapp/lib/python2.7/site-packages/kivy/core/text/text_layout.so.o
myapp/lib/python2.7/site-packages/kivy/graphics/gl_instructions.so.o

https://groups.google.com/forum/#!topic/kivy-users/l9wVUhco98s

These files appear to be left over from the compilation and can safely be removed, but should be removed by default.

**Comment by FiveToFight** [comment]
I'm seeing this issue but with '.so' files rather than '.so.o' files. They're all coming from modules that i'm using (requests, PIL, etc.) which are found in the folder YourApp/modulename/something.so

A lot of answers to fixing the error mentioned above say to move the files (in this case, the folder YourApp) from the Copy Bundle Resources build phase in Xcode to the Link Binary With Libraries build phase. But Xcode complains that the it doesn't know what to do with that folder. Any ideas why I'm seeing this error when trying to upload to the App Store?

<img width="752" alt="screen shot 2018-10-28 at 9 49 57 am" src="https://user-images.githubusercontent.com/37519914/47620086-41026300-daa3-11e8-96c9-0a269569c4c5.png">

**Comment by Zen-CODE** [comment]
I would guess that the linking is not pulling through. I'd suggest not moving the folder and try to manually make a link to 'event.so'? Have you built successfully before? Or are you setting up the build on that machine for the first time?

**Comment by Dirk-Sandberg** [comment]
It builds fine when I'm trying to run it on my own device, but I haven't gotten this to work when uploading to the app store. I removed the whole YourApp folder from the Copy Bundle Resources phase, which makes it able to upload to the app store, but the app won't actually run like on my phone since it needs those files, so I put YourApp back in Copy Bundle Resources.

If I try to add .so files inside the "Link Binary with Libraries" phase, I get a warning saying that that file is skipped because Xcode doesn't know how to handle it.
<img width="272" alt="screen shot 2018-10-28 at 12 03 55 pm" src="https://user-images.githubusercontent.com/37519914/47620642-96da0980-daa9-11e8-8e4a-be2caf596d7b.png">

**Comment by Zen-CODE** [comment]
Sorry, not sure why that is. Creating a new ticket might be an idea, but it looks like more of an XCode issue that a kivy one....
