### ISSUE TITLE
Implementing twisted and autobahn related recipes

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy-ios#220]
Hi,

I currently try (from time to time) to implement recipes for installing ``autobahn`` and ``twisted``. Basic implementation is already done here https://github.com/rnixx/kivy-ios/tree/twisted_recipe/recipes

Package dependencies looks like:

    autobahn==0.16.0
        * six
        * txaio
    cffi==1.8.3
        * pycparser
    cryptography==1.5.2
        * cffi
        * enum34
        * idna
        * pyasn1
        * six
    enum34==1.1.6
        * NONE
    idna==2.1
        * NONE
    ipaddress==1.0.17
        * NONE
    pyasn1==0.1.9
        * ipaddress
    pycparser==2.14
        * NONE
    pyOpenSSL==16.1.0
        * cryptography
    six==1.10.0
        * NONE
    Twisted==16.4.1
        * zope.interface
    txaio==2.5.1
        * six
    zope.interface==4.3.2
        * setuptools

The recipes for these packages are basically implemented and define the dependencies properly.

The pure python package related recipes install successfully.

I also had a look how ``python-for-android`` handles twisted installation and then I came along ``install_in_hostpython`` flag on it's recipes, which is set for ``cffi``, ``pycparser`` and ``twisted`` among some other unrelated recipes.

``pycryptography`` tries to download and build it's dependencies inside it's build folder if dependencies are missing, thus I tried to install ``cffi`` and ``pycparser`` in hostpython as well to avoid this. For ``pycparser`` this works, while ``cffi`` causes troubles.

The target builds of ``cffi`` work (I deployed to an iPad, imported ``cffi`` and instanciated a ``cffi.api.FFI()`` object).

The installation in hostpython installs, import works as well, but instanciating ``cffi.api.FFI()`` fails:

    myhost:kivy-ios user$ ./dist/hostpython/bin/python
    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Python 2.7.1 (r271:86832, Nov  4 2016, 10:41:44)
    [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cffi
    >>> cffi.api.FFI()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/.../kivy-ios/dist/hostpython/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
        import _cffi_backend as backend
    ImportError: dynamic module does not define init function (init_cffi_backend)

You can find the code here https://github.com/rnixx/kivy-ios/blob/twisted_recipe/recipes/cffi/__init__.py

Any advice and or help how to fix this is really appreciated.

Thanks

**Comment by rnixx** [comment]
Findings after more experiments -> Skipping the ``dynload.patch`` in ``hostpython`` enabled dynamic so loading in site-packages again which would partly solve one of my recent problems, especially finding the compiled extensions of ``cffi`` which make ``cffi.api.FFI()`` instanciation work (subsequently needed by ``cryptography`` to build it's own extensions).

This raises the question why hostpython is compiled with almost the same set of patches as the target python? If I understood right hostpython is only used on local machine and never in distributed app on target platform, right?

**Comment by jegger** [comment]
I saw you did some additional work since your last update. Tito did some work to get setuptools / cryptography going in the branch https://github.com/kivy/kivy-ios/tree/recipe-setuptools-cryptography . Based on this branch I needed to do a small fix for zope, cryptography and twisted (https://github.com/jegger/kivy-ios/commit/2398fe438b1ff0d501ea3202b8370710e6a3d887) to get it to compile properly.

What I did after that:
- cleaned dist and build folder
- ./toolchain.py build openssl cryptography pycrypto autobahn kivy
- ./toolchain.py create <proj-name> /path/to/autobahn-proj
- built for real-target (iPhone) and simulator

On both targets I am running into this error:
`Traceback (most recent call last):
   File "kivy-ios-crypto/autobahn-ios/YourApp/main.py", line 44, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/client.py", line 31, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/session.py", line 17, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/sessionclient.py", line 125, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/libs/autobahn/twisted/websocket.py", line 527, in connectWS
   File "kivy-ios-crypto/autobahn-ios/YourApp/libs/twisted/internet/ssl.py", line 59, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/libs/OpenSSL/__init__.py", line 8, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/libs/OpenSSL/rand.py", line 11, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/libs/OpenSSL/_util.py", line 6, in <module>
   File "kivy-ios-crypto/autobahn-ios/YourApp/libs/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
   File "<string>", line 32, in load_module
ImportError: dynamic module does not define init function (init_openssl)`

So the general questions are:
- Did you got it working with SSL support?
- Am I doing something generally wrong?

**Comment by keavin7** [comment]
Hey fellas,

Been wondering this myself. I'm looking at the Android Recipe Here:
https://github.com/kivy/python-for-android/blob/master/pythonforandroid/recipes/twisted/__init__.py

`
import glob
from pythonforandroid.toolchain import (
    CythonRecipe,
    Recipe,
    current_directory,
    info,
    shprint,
)
from os.path import join
import sh


class TwistedRecipe(CythonRecipe):
    version = '16.0.0'
    url = 'https://github.com/twisted/twisted/archive/twisted-{version}.tar.gz'

    depends = ['setuptools', 'zope_interface']

    call_hostpython_via_targetpython = False
    install_in_hostpython = True

    def prebuild_arch(self, arch):
        super(TwistedRecipe, self).prebuild_arch(arch)
        # TODO Need to whitelist tty.pyo and termios.so here
        print('Should remove twisted tests etc. here, but skipping for now')

    def get_recipe_env(self, arch):
        env = super(TwistedRecipe, self).get_recipe_env(arch)
        # We add BUILDLIB_PATH to PYTHONPATH so twisted can find _io.so
        env['PYTHONPATH'] = ':'.join([
            self.ctx.get_site_packages_dir(),
            env['BUILDLIB_PATH'],
        ])
        return env

recipe = TwistedRecipe()`

**Comment by keavin7** [comment]
I think this is the solution, although I've yet to implement it... I would think that a recipe would need to essentially follow this person's instructions?

https://groups.google.com/forum/#!topic/kivy-users/8cNfNJZL-XA

> Twisted can be easily run as a pure-python module. It does have some arm7-specific components for other obscure platforms (like windows or fancy signal handling), but they can all be ignored.
> 
> Solving this for me included simply copying the entire /usr/lib/python2.7/dist-packages/twisted directory from my linux machine into my application directory. Then you just delete any library files (*.so or *.a) that you see in the twisted directory and leave just the python files.
> 
> Then, you modify your Kivy application's path to be able to import the "local" twisted folder like this:
> 
> import sys
> cwd = # path to the current working directory of main.py running on the phone
> sys.path = [ cwd ] + sys.path
> import twisted
> 
> NOTE: you must do exactly the same thing for the "zope" folder in dist-packages as well. Same instructions.
> 
> That worked for me.

**Comment by rnixx** [comment]
@jegger 

> Did you got it working with SSL support?

That's what we are working on (even if slowly). For SSL support in twisted pyopenSSL is needed which depends on cryptography which currently causes troubles. @tito did some work in a branch I still need to test (which I hopefully can do at the beginning of feb)

You're welcome to help out with this as well ;)

@keavin7 

Copying twisted would work, as long as you don't need SSL. And I strongly doubt that someone wants do do non SSL networking in 2017.

Another option would be to reimplement ``twisted.internet.ssl`` (https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/ssl.py) not using pyopenSSL, but I'd consider this a hard task. Better get cryptography recipe working.

**Comment by rodjun** [comment]
For anyone following the guide that @keavin7 quoted, some notes to actually get it working:

That directory thing is not necessary at all, don't do it.

You actually need to move 4 dependencies to the place where main.py is located, they are:

* constantly
* incremental
* twisted
* zope

Also make sure that you create a __init__.py file inside the zope folder or you will get an import error ("can't find zope.interfaces").

like others mentioned, SSL does not work so don't use this for important stuff, my use case is just passing some data from my computer to other computers or mobile devices, it's also nothing sensitive so i have no problems with the lack of SSL.

**Comment by Zen-CODE** [comment]
PR's to add these welcome. Closing the ticket due to inactivity...
