### ISSUE TITLE
Xcode Build failing

### ISSUE THREAD

**Issue by TheDocter** [kivy/kivy-ios#264]
It hase been a while sense I actually had this working. I had the same issue and for the life of me I can't remember how I fixed it.

Python Version 2.7.12
Xcode Version: 8.3.3

> Showing Recent Messages
> rsync warning: some files vanished before they could be transferred (code 24) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(996) [sender=2.6.9]
> 
> 
> Command /bin/sh failed with exit code 24

I've searched on the repository issues and the kivy users google group. I have yet to find anything that helped. Anyone have any ideas? If you need anything else let me know and I'll get it posted for you.

**Comment by tonibagur** [comment]
I had the same issue. I think that when you create the project with the command:
./toolchain.py create <Project-Name> <python_directory>, I thought that directory is the directory where you wan't to place the xcode project but it turns out that this framework asumes that you have a <python_directory> whith all .py files. When you build the project this .py files are automatically compiled to .pyo files and copied to the xcodeproj folder, is in this stage where you are having problems.
My advice is to create a dir with your python files <python_directory> and then run
 ./toolchain.py create <Project-Name> <python_directory>
this will create a <Project-Name-ios> folder with the xcode project ready to compile again.
If you need more help, please, let me know.

**Comment by TheDocter** [comment]
I've moved onto Switch for iOS development. As much as I love Python and Kivy. It was just slowing my development down as I kept running into issues that I had to fix. Thanks for the reply though.
