### ISSUE TITLE
Cannot build app after creating xcode project

### ISSUE THREAD

**Issue by sarpraiz** [kivy/kivy-ios#277]
I've managed to build kivy-ios and create the xcode project linked to my directory with main.py. However, when I click on the Play button or Product >> Run, it gives me a directory not found error.

error: /Users/sarpraiz/kivy-ios/dist/root/python/lib: No such file or directory

When I checked, the kivy-ios/dist/root directory is just empty?

Xcode version: 9.2
OSX version: 10.13.2

**Comment by danmacnaughtan** [comment]
So I tried the Touchtracer demo about 10 days ago. I had a similar error (among many others), but after digging through past issues I managed to get the project working ([helpful link](https://github.com/kivy/kivy-ios/pull/268)). (I'm running macOS 10.13.2, Xcode 9.2, and I am using python 2.7.14 from python.org rather than the default macOS version)

My recommended checklist of things to try:
- Try rebuilding kivy with cython 0.23
- Disable bitcode in the Xcode project settings (Enable Bitcode--No)
- Add additional frameworks (project settings, under general->linked frameworks and libraries): libc++, libsqlite3, libz, CoreMotion
- Make sure framework search paths in the Xcode project settings are pointing to kivy-ios/dist/lib

**Comment by Neuroverb** [comment]
Thank you danmacnaughtan, this totally worked! 

Xcode 9.2
OSX 10.12.6

Initially I was getting so many errors installing kivy-ios and then building App so I was thrilled to see the iPhone simulator appearing and the apprunning!

**Comment by sarpraiz** [comment]
I'm still having problems building it :( when I try to build kivy, it stops at this error:

> checking size of uintptr_t... configure: error: in `/Users/sarpraiz/kivy-ios/build/python/i386/Python-2.7.1':
> configure: error: cannot compute sizeof (uintptr_t)
> 

And when I search 'uintptr_t' in config.log, I get this result

> configure:7099: checking for uintptr_t
> if (sizeof ((uintptr_t)))
> | if (sizeof ((uintptr_t)))
> configure:7116: checking size of uintptr_t
> | #define HAVE_UINTPTR_T 1
> | static int test_array [1 - 2 * !(((long int) (sizeof (uintptr_t))) >= 0)];
> static int test_array [1 - 2 * !(((long int) (sizeof (uintptr_t))) < 0)];
> | #define HAVE_UINTPTR_T 1
> | static int test_array [1 - 2 * !(((long int) (sizeof (uintptr_t))) < 0)];
> configure:7129: error: cannot compute sizeof (uintptr_t)
> ac_cv_type_uintptr_t=yes
> #define HAVE_UINTPTR_T 1

**Comment by sarpraiz** [comment]
Thanks danmacnaughtan! I realise that my kivy build wasn't working to begin with, although downgrading to Cython 0.23 still doesn't allow me
