### ISSUE TITLE
Latest commit broke kivy-ios!!!

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy-ios#310]
After the command **_./toolchain.py build python3 kivy_** everything is successfully built! But when trying to run a simple Kivy example in the XCode, it gives an error - 

```python
CpResource /Users/macbookair/Opt/kivy-ios/dist/hostpython/include /Users/macbookair/Library/Developer/Xcode/DerivedData/helloworld-bxowofzfggzdeocgvyelkhobyjar/Build/Products/Debug-iphonesimulator/helloworld.app/include
    cd /Users/macbookair/Opt/kivy-ios/helloworld-ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/macbookair/Opt/kivy-ios/dist/hostpython/include /Users/macbookair/Library/Developer/Xcode/DerivedData/helloworld-bxowofzfggzdeocgvyelkhobyjar/Build/Products/Debug-iphonesimulator/helloworld.app

**error: /Users/macbookair/Opt/kivy-ios/dist/hostpython/include: No such file or directory**
```
In the **_kivy-ios/dist_** directory there is only **_hostpython3_**

![2018-11-11 15 43 38](https://user-images.githubusercontent.com/16930280/48313124-fca9b380-e5c8-11e8-9e1e-93d1ea7360f1.png)

If I use the command **_./toolchain.py build python kivy_** getting another error - 
```python
/Users/macbookair/Library/Developer/Xcode/DerivedData/helloworld-bxowofzfggzdeocgvyelkhobyjar/Build/Intermediates.noindex/helloworld.build/Debug-iphonesimulator/helloworld.build/Script-113D17E2153E3DB5001310A6.sh: line 2: 

/Users/macbookair/Opt/kivy-ios/dist/hostpython3/bin/python: No such file or directory
```

In this case, the **_dist_** directory looks like this - 
![2018-11-11 18 19 38](https://user-images.githubusercontent.com/16930280/48314714-5bc5f300-e5de-11e8-95df-7a00102e1e9f.png)

**Comment by iBeef** [comment]
Same issue here :(.

**Comment by HeaTTheatR** [comment]
> Same issue here :(.

I don’t understand why the developers ignore more than half of the questions ... I don’t understand why the developers don’t provide a tutorial on creating packages for the iPhone and pretend that everything works?

**Comment by HeaTTheatR** [comment]
> > > Same issue here :(.
> > 
> > 
> > I don’t understand why the developers ignore more than half of the questions ... I don’t understand why the developers don’t provide a tutorial on creating packages for the iPhone and pretend that everything works?
> 
> I think that's a little harsh, at the end of the day from what I understand these guys do it in their own time and provide us a way to make great apps using a language that otherwise you wouldn't be able to. It saves me writing apps for two platforms separately with languages I'm not particularly familiar with.
> 
> Personally I've never written code and there hasn't been a bug or two in it which needed ironing out. If anything I wish I was skilled enough to be able to contribute to this project so providing bugs etc. isn't a bad way to do so.

I love Kiyy too. And I try to simplify application development as much as possible - https://github.com/HeaTTheatR/KivyMD

I write articles for people who are just starting to work with Kivy - https://habr.com/users/heattheatr/posts/

And I also popularize this framework. But I don’t understand why developers don’t really explain how to build packages for iPhones! It seems that Kivy is for Android only: (

**Comment by cruor99** [comment]
I disagree with your last sentence. According to the Kivy Discord, kivy-ios is actively being worked upon right now - in order to successfully make the transition to python3 and it is the focus of @tito, right now. 

I'm not entirely sure why you haven't been able to build properly until now, but I have built and pushed out several updates to apps and a new app over testflight in that timespan.

To go on-topic, building for python2 will give you a similar issue of hostpython3 missing. I found that copying either of them to the respective other will let the build process continue, and works from there.

**Comment by HeaTTheatR** [comment]
> I disagree with your last sentence. According to the Kivy Discord, kivy-ios is actively being worked upon right now - in order to successfully make the transition to python3 and it is the focus of @tito, right now.
> 
> I'm not entirely sure why you haven't been able to build properly until now, but I have built and pushed out several updates to apps and a new app over testflight in that timespan.
> 
> To go on-topic, building for python2 will give you a similar issue of hostpython3 missing. I found that copying either of them to the respective other will let the build process continue, and works from there.

Could you give instructions on how you create the package for the iPhone? 

**1 - I created the Hello World folder with files:**

![2018-11-14 22 49 12](https://user-images.githubusercontent.com/16930280/48508403-8a063580-e85f-11e8-9d02-ba52fa65dbd0.png)

**2 - Contains file buildozer.spec:**

```python
[app]

title = HelloWorld
package.name = helloworld
package.domain = org.kivy
source.dir = .
(str) Application versioning (method 2)
version.regex = __version__ = ['"](.*)['"]
version.filename = %(source.dir)s/main.py
author = © Copyright Info
osx.python_version = 2
osx.kivy_version = 1.10.1
ios.kivy_ios_dir = /Users/macbookair/Opt/kivy-iosos.codesign.debug = "iPhone Developer: Ajena Groshin (J5PTLM7R37)"
ios.codesign.release = %(ios.codesign.debug)s

[buildozer]

log_level = 2
```

**3 - Create XCode project:**

```pyrhon
./toolchain.py create HelloWorld /Users/macbookair/Projects/HelloWorld
```

![2018-11-14 23 00 15](https://user-images.githubusercontent.com/16930280/48509043-18c78200-e861-11e8-84c3-4a2a3ea19656.png)

Now the question is: should I run the application in the Xcode before building the iPhone package?

![2018-11-14 23 03 17](https://user-images.githubusercontent.com/16930280/48509468-452fce00-e862-11e8-9360-15fe72dce5e0.png)

Or do not open Xcode at all and immediately run the command:

```python
cd /Users/macbookair/Projects/HelloWorld
buildozer ios release
```
About these simple actions is not written anywhere!

**Comment by tito** [comment]
The latest merge renamed hostpython and python to hostpython2 and python2.
This is due to the support of Python 3 in the toolchain.

However, i didn't though nor didn't write down what to change to make it work on existing projects, my bad. I'll retry both build just to be sure master is working (i tried to do travis build, but the current log generated is too large for travis).

If possible, try to regenerate your project with the `./toolchain.py create`

**Comment by tito** [comment]
@HeaTTheatR we lack of contributors, and i wasn't here on the project much this past few years, but it is going to change. I just remind you that we are all working here in our free time to make the project working. Free as less times for friends, familly, musics, etc. All the platforms are moving, and OSS world also changes. Like Python Crystax goes unmaintained, Android requires API 26 minimum for 1st november, new Android NDK breaks the build, new XCode clang breaks the build... And the fact that we weren't compatible with Python 3 on iOS too.

Making a toolchain is hard, and take times. I took less than 2 weeks unpaid for doing PyOBJUS support for Python 3, as well as adding Python 3 support for Kivy iOS.

Now that you have an issue, please retry from a fresh clone. Most of the issue i see here are because of using an old project, like the include, but i may be wrong.

The latest master are not compatible with previous. Either get back to the revision before the merge, or just recreate your project on latest template.

**Comment by HeaTTheatR** [comment]
> The latest master are not compatible with previous. Either get back to the revision before the merge, or just recreate your project on latest template.

@tito The fact is that I am creating a project from scratch with an updated kivy-ios!

I understand! My question also contributes to the development of the project. After the last commit - there was a problem! And, apparently, he will not give the opportunity to build and manage projects.

I am expounding the problem in detail:


### Build with Python 3

![2018-11-16 9 56 26](https://user-images.githubusercontent.com/16930280/48602962-ecf1ec80-e985-11e8-9e40-71e8f6f3cba0.png)

The build was successful!

![2018-11-16 10 30 30](https://user-images.githubusercontent.com/16930280/48604377-b79bcd80-e98a-11e8-8f06-4258fdd203dc.png)

Create a new project:

![2018-11-16 10 32 48](https://user-images.githubusercontent.com/16930280/48604460-0184b380-e98b-11e8-8a8a-4a00ebf8bfd5.png)

Project successfully created!

![2018-11-16 10 34 26](https://user-images.githubusercontent.com/16930280/48604518-3264e880-e98b-11e8-954e-c59331ac3c4d.png)

Open project:

![2018-11-16 10 36 02](https://user-images.githubusercontent.com/16930280/48604613-6d671c00-e98b-11e8-9ada-deacc31ca2d2.png)

Run project:

![dddd](https://user-images.githubusercontent.com/16930280/48605022-9fc54900-e98c-11e8-93be-917aecd8f672.png)

Build Failed:

![2018-11-16 10 45 34](https://user-images.githubusercontent.com/16930280/48605060-c2576200-e98c-11e8-89f8-3ec2b57aece9.png)


### Build with Python 2

Compile:

![2018-11-16 10 56 24](https://user-images.githubusercontent.com/16930280/48605608-50801800-e98e-11e8-9009-8eb7c3d0532e.png)

The build was successful!

![2018-11-16 11 33 36](https://user-images.githubusercontent.com/16930280/48608428-91c6f680-e993-11e8-8768-b61ee1a715e2.png)

Create a new project:

![2018-11-16 11 36 53](https://user-images.githubusercontent.com/16930280/48608730-ec605280-e993-11e8-9223-83469e483b95.png)

Open and run project (build failed):

![2018-11-16 11 39 34](https://user-images.githubusercontent.com/16930280/48609053-50831680-e994-11e8-9cc6-6cefecb764b0.png)

If we now try to add the recipe Python3, we get an error:

![2018-11-16 11 46 54](https://user-images.githubusercontent.com/16930280/48609989-53323b80-e995-11e8-91cd-d8b9e5821b8a.png)

![2018-11-16 11 48 26](https://user-images.githubusercontent.com/16930280/48610159-8b397e80-e995-11e8-9f90-f7279c94ec73.png)

Therefore, we can conclude that at the moment kivy-ios is broken!

**Comment by tito** [comment]
Your error indicate that on the same "clone", you first tried to use python2, so it is registered as a python2 build. Clean the build/dist directory (or toolchain.py distclean) and retry. You can't have a toolchain with both python2 and python3 binaries

**Comment by HeaTTheatR** [comment]
> Your error indicate that on the same "clone", you first tried to use python2, so it is registered as a python2 build. Clean the build/dist directory (or toolchain.py distclean) and retry. You can't have a toolchain with both python2 and python3 binaries.

@tito The fact is that with each build I re-clone kivy-ios, i.e. Assembly is done from scratch.

**Comment by tito** [comment]
Yes, but you did something wrong for the latests screenshots, as mixing a build with python2/hostpython2 and try to do python3/hostpython3 after. This is why you have the message. I'll ignore that one.

Only the include in xcode may still reference hostpython instead of hostpython2 or hostpython3. I'm checking this right now.

**Comment by tito** [comment]
@HeaTTheatR before my build finish, can you on the python3/kivy build with the issue on the include path, close xcode, edit the xcodeproj to remove the line with "hostpython/include", and retry?

**Comment by HeaTTheatR** [comment]
@tito I'll try it now...

**Comment by tito** [comment]
@HeaTTheatR fixed in master. Thoses lines wasn't needed anymore, and got removed in master. Please pull or clone, and recreate the project with latest template.

**Comment by HeaTTheatR** [comment]
@tito Thank you for responding to this problem! I'll check it out a little later.
