### ISSUE TITLE
Pandas doesn’t work. 

### ISSUE THREAD

**Issue by williamrainer** [kivy/kivy-ios#408]
I’ve run 
$ python3 toolchain.py pip3 install pandas
And it says 
“ImportError: Unable to import required dependencies: numpy. Importing the numpy c-extensions failed”
Do I need the pandas recipe? I really need it! :(

**Comment by krusaderjake** [comment]
@williamrainer I'm curious, did you install the numpy build recipe since numpy is a dependency of pandas?
`./toolchain.py build numpy`

I was getting the same error you have above before I installed the numpy build recipe, then I started getting different errors lol that I mention in my issue: https://github.com/kivy/kivy-ios/issues/412

**Comment by williamrainer** [comment]
I hadn't installed the NumPy build recipe. But yeah, even after installing it I still got errors. So I just got rid of Pandas and changed my code to only use NumPy.

I found this [`link](https://github.com/kivy/python-for-android/issues/1241), which seems to suggest that Pandas won't work...

**Comment by Zen-CODE** [comment]
You would need a recipe as pandas is not officially supported.

But please post the question on the Kivy forum here: https://groups.google.com/forum/#!forum/kivy-users

This issue tracker is reserved for reporting demonstrable faults in kivy-ios. Thanks.
