### ISSUE TITLE
Add external libraries to ios app

### ISSUE THREAD

**Issue by simonjuleseric2** [kivy/kivy-ios#497]
Is there any way to add external libraries (that are not in the recipe folder on the kivy ios GitHub) to the ios app with kivy? I'm having trouble especially with OpenCV and Tensorflow/Keras. Was anyone able to do this?

**Comment by Zen-CODE** [comment]
You could do the following:
1. Clone the repo
2. Add your own recipes in the recipes folder
3. Build and run your toolchain from that checkout.

There is also a pending PR that would add this: https://github.com/kivy/kivy-ios/pull/417

Otherwise, if you have further questions, please post them on the  Kivy forum here: https://groups.google.com/forum/#!forum/kivy-users

Thanks.
