### ISSUE TITLE
iOS Build Failed. rsync warning: some files vanished before they could be transferred (code 24) 

### ISSUE THREAD

**Issue by gargsaar** [kivy/kivy-ios#513]
iOS Build Failed. Error:

```
rsync warning: some files vanished before they could be transferred (code 24) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
```
Went through the advice posted at Issue #264 on the same topic, but no help.

**Comment by ArtOlender** [comment]
I'm new to kivy-ios as well.  But, this also happened to me when I did the "toolchain build" in my source directory (or anywhere in the file tree under my source directory).  I think this is because the "build" and "dist" directories that are created in the current working directory by the "toolchain build" process get recursively included in the project created by "toolchain create", which in turn confuses rsync when it's copying files around.
So, for me, the key was to do the "toolchain build" outside my application source directory tree.

% cd <to a directory outside my application directory tree>
% toolchain build python3 kivy openssl
% toolchain create <my_app_name>  <full_path_to_my_app_source_directory>
% open <my_app_name>-ios/<my_app_name>.xcodeproj
then the IOS build completed successfully!

**Comment by garantor** [comment]
This just saved me @ArtOlender, thanks for sharing
