### ISSUE TITLE
invalid python3 symlink

### ISSUE THREAD

**Issue by Arban960** [kivy/kivy-ios#600]
When I try to run the project on a simulator, I get an invalid python3 symlink error. Does anybody else have this problem?

**Comment by misl6** [comment]
The issue was solved through #ios-support (Discord).

The user previously included its virtualenv into the package.

If anyone else is encountering this issue, In Xcode, under the "Build Phases" section, We have a "Run Script" section, where the developer has to edit the rsync command accordingly to its app code folder, by excluding via  `--exclude` the unneeded or offending folders/files.
