### ISSUE TITLE
error when I run toolchain build kiva python3

### ISSUE THREAD

**Issue by sltoo777** [kivy/kivy-ios#629]
[INFO    ] Building with 8 processes, where supported
[INFO    ] Want to build ['kivy', 'python3']
[INFO    ] Loaded recipe kivy (depends of ['sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios', 'pyobjus', 'python', 'host_setuptools3'], optional are [])
[INFO    ] Loaded recipe python3 (depends of ['hostpython3', 'libffi', 'openssl'], optional are [])
[INFO    ] Loaded recipe sdl2 (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
[INFO    ] Loaded recipe ios (depends of ['python'], optional are [])
[INFO    ] Loaded recipe pyobjus (depends of ['python'], optional are [])
[INFO    ] Loaded recipe python (depends of ['python3'], optional are [])
[INFO    ] Loaded recipe host_setuptools3 (depends of ['openssl', 'hostpython3', 'python3'], optional are [])
[INFO    ] Loaded recipe hostpython3 (depends of ['hostlibffi', 'hostopenssl'], optional are [])
[INFO    ] Loaded recipe libffi (depends of [], optional are [])
[INFO    ] Loaded recipe openssl (depends of [], optional are [])
[INFO    ] Loaded recipe freetype (depends of [], optional are [])
[INFO    ] Loaded recipe hostlibffi (depends of [], optional are [])
[INFO    ] Loaded recipe hostopenssl (depends of [], optional are [])
[INFO    ] Build order is ['freetype', 'hostlibffi', 'hostopenssl', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'host_setuptools3', 'python', 'ios', 'pyobjus', 'kivy']
[INFO    ] Recipe order is ['freetype', 'hostlibffi', 'hostopenssl', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'host_setuptools3', 'ios', 'pyobjus', 'kivy']
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/hostlibffi
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Global: hostpython located at /Users/mahdi/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/mahdi/dist/hostpython3/bin/pgen
[INFO    ] Include dir added: common/sdl2_image
[INFO    ] Include dir added: common/sdl2_mixer
[INFO    ] Include dir added: common/sdl2_ttf
[DEBUG   ] Cached result: Download freetype. Ignoring
[INFO    ] Extract freetype
[INFO    ] Extract freetype for x86_64
[WARNING ] Error extracting the archive /Users/mahdi/.cache/freetype-freetype-2.5.5.tar.bz2
[WARNING ] This is usually caused by a corrupt download. The file will be removed and re-downloaded on the next run.
[WARNING ] /Users/mahdi/.cache/freetype-freetype-2.5.5.tar.bz2
Traceback (most recent call last):
  File "/opt/homebrew/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1519, in main
    ToolchainCL()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1276, in __init__
    getattr(self, args.command)()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1337, in build
    build_recipes(args.recipe, ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 1127, in build_recipes
    recipe.execute()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 698, in execute
    self.extract()
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 742, in extract
    self.extract_arch(arch.arch)
  File "/opt/homebrew/lib/python3.9/site-packages/kivy_ios/toolchain.py", line 746, in extract_arch
    dest_dir = join(build_dir, self.archive_root)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by misl6** [comment]
```
[WARNING ] Error extracting the archive /Users/mahdi/.cache/freetype-freetype-2.5.5.tar.bz2
[WARNING ] This is usually caused by a corrupt download. The file will be removed and re-downloaded on the next run.
[WARNING ] /Users/mahdi/.cache/freetype-freetype-2.5.5.tar.bz2
```

As stated by these lines, the download of the specified package is probably corrupt.
Can you try to delete it and re-start the toolchain build?

P.S. : Another user had a similar issue on freetype today, so it is probably a temporary failure on freetype mirrors.

**Comment by misl6** [comment]
@sltoo777 looks like is another kind of issue. Can you try to follow all the suggested steps in docs and re-open a separate issue if help is still needed? Remember to follow the bug report completely, by adding your versions and runnable example.

**Comment by reddawnfreedom** [comment]
I'm getting the same original issue with the FreeType url even with the master. As Follows:
(kivyProject) user@ kivyProject % toolchain build python3 kivy                                               
[INFO    ] Building with 4 processes, where supported
[INFO    ] Want to build ['python3', 'kivy']
[INFO    ] Loaded recipe python3 (depends of ['hostpython3', 'libffi', 'openssl'], optional are [])
[INFO    ] Loaded recipe kivy (depends of ['sdl2', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'ios', 'pyobjus', 'python', 'host_setuptools3'], optional are [])
[INFO    ] Loaded recipe hostpython3 (depends of ['hostlibffi', 'hostopenssl'], optional are [])
[INFO    ] Loaded recipe libffi (depends of [], optional are [])
[INFO    ] Loaded recipe openssl (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2 (depends of [], optional are [])
[INFO    ] Loaded recipe sdl2_image (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_mixer (depends of ['sdl2'], optional are [])
[INFO    ] Loaded recipe sdl2_ttf (depends of ['sdl2', 'freetype'], optional are [])
[INFO    ] Loaded recipe ios (depends of ['python'], optional are [])
[INFO    ] Loaded recipe pyobjus (depends of ['python'], optional are [])
[INFO    ] Loaded recipe python (depends of ['python3'], optional are [])
[INFO    ] Loaded recipe host_setuptools3 (depends of ['openssl', 'hostpython3', 'python3'], optional are [])
[INFO    ] Loaded recipe hostlibffi (depends of [], optional are [])
[INFO    ] Loaded recipe hostopenssl (depends of [], optional are [])
[INFO    ] Loaded recipe freetype (depends of [], optional are [])
[INFO    ] Build order is ['freetype', 'hostlibffi', 'hostopenssl', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'host_setuptools3', 'python', 'ios', 'pyobjus', 'kivy']
[INFO    ] Recipe order is ['freetype', 'hostlibffi', 'hostopenssl', 'libffi', 'openssl', 'sdl2', 'hostpython3', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'python3', 'host_setuptools3', 'ios', 'pyobjus', 'kivy']
[INFO    ] Include dir added: {arch.arch}/freetype
[INFO    ] Include dir added: {arch.arch}/hostlibffi
[INFO    ] Include dir added: {arch.arch}/ffi
[INFO    ] Include dir added: {arch.arch}/openssl
[INFO    ] Include dir added: common/sdl2
[INFO    ] Global: hostpython located at /Users/user/Documents/Program_Projects/kivy/kivyProject/dist/hostpython3/bin/python
[INFO    ] Global: hostpgen located at /Users/user/Documents/Program_Projects/kivy/kivyProject/dist/hostpython3/bin/pgen
[INFO    ] Include dir added: common/sdl2_image
[INFO    ] Include dir added: common/sdl2_mixer
[INFO    ] Include dir added: common/sdl2_ttf
[DEBUG   ] Cached result: Download freetype. Ignoring
[INFO    ] Extract freetype
[INFO    ] Extract freetype for x86_64
[WARNING ] Error extracting the archive /Users/user/Documents/Program_Projects/kivy/kivyProject/.cache/freetype-freetype-2.5.5.tar.bz2
[WARNING ] This is usually caused by a corrupt download. The file will be removed and re-downloaded on the next run.
[WARNING ] /Users/user/Documents/Program_Projects/kivy/kivyProject/.cache/freetype-freetype-2.5.5.tar.bz2
Traceback (most recent call last):
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/bin/toolchain", line 11, in <module>
    load_entry_point('kivy-ios==1.3.0.dev0', 'console_scripts', 'toolchain')()
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1536, in main
    ToolchainCL()
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1293, in __init__
    getattr(self, args.command)()
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1354, in build
    build_recipes(args.recipe, ctx)
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 1136, in build_recipes
    recipe.execute()
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 701, in execute
    self.extract()
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 73, in _cache_execution
    f(self, *args, **kwargs)
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 746, in extract
    self.extract_arch(arch.arch)
  File "/Users/user/Documents/Program_Projects/kivy/kivyProject/lib/python3.8/site-packages/kivy_ios/toolchain.py", line 750, in extract_arch
    dest_dir = join(build_dir, self.archive_root)
  File "/Users/user/opt/anaconda3/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/user/opt/anaconda3/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by reddawnfreedom** [comment]
Never mind I'm an idiot. Did "toolchain clean" and tried again and its working now.

**Comment by mamunabcoder** [comment]
I have found another issue when try to install:
pip install https://github.com/kivy/kivy-ios/archive/refs/heads/master.zip

Below error found:

RAN: /usr/bin/patch -t -d /Users/bjitlimited/kivy_rnd/build/hostlibffi/x86_64/libffi-3.2.1 -p1 -i /Users/bjitlimited/kivy_rnd/kivy_venv/lib/python3.9/site-packages/kivy_ios/recipes/hostlibffi/fix-win32-unreferenced-symbol.patch

  STDOUT:


  STDERR:
/usr/bin/patch: **** Can't open patch file /Users/bjitlimited/kivy_rnd/kivy_venv/lib/python3.9/site-packages/kivy_ios/recipes/hostlibffi/fix-win32-unreferenced-symbol.patch : No such file or directory
