### ISSUE TITLE
Mac OS 12.3.1 Apple Silicon 

### ISSUE THREAD

**Issue by jhay06** [kivy/kivy-ios#704]
Hi ,
   Would like to request to support the latest MAc OS 12.3.1 with Apple silicon chip , 

for information, the latest version osx removes /usr/bin/python  which is required with libffi and other recipes .

and now i cannot make it work on the latest mac os version because only /usr/bin/python3 is present on the system

**Comment by misl6** [comment]
Hi @jhay06 ,

Support for macOS 12.3.1 has already been added in https://github.com/kivy/kivy-ios/pull/688

In order to use a development version, please follow this guide:
https://github.com/kivy/kivy-ios#development

Feel free to join our [Discord Chat](https://chat.kivy.org) if you need some help or advice.
