### ISSUE TITLE
Is there any working lxml alternative?

### ISSUE THREAD

**Issue by sharpordie** [kivy/kivy-ios#722]

**Comment by misl6** [comment]
Hi @sharpordie it highly depends on your needs.

Feel free to join us on [Discord](https://chat.kivy.org), our community may be helpful in order to check for a valid alternative, based on your use case.

Considering that a feature-request for the lxml recipe is already open here: https://github.com/kivy/kivy-ios/issues/633, I will close this issue as a support one.
